---
manual:Javascript
version:0
lang:zh
rawUrl:https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally
---



这篇翻译不完整。请帮忙从英语[翻译这篇文章]45984 "")。





`**finally()**`方法返回一个[`Promise`]4107 "Promise 对象用于表示一个异步操作的最终状态（完成或失败），以及其返回的值。")，在执行[`then()`]41433 "then() 方法返回一个  Promise 。它最多需要有两个参数：Promise 的成功和失败情况的回调函数。")和[`catch()`]42294 "catch() 方法返回一个Promise，并且处理拒绝的情况。它的行为与调用Promise.prototype.then(undefined, onRejected) 相同。 (事实上, calling obj.catch(onRejected) 内部calls obj.then(undefined, onRejected)).")后，都会执行**`finally`**指定的回调函数。避免同样的语句需要在[`then()`]41433 "then() 方法返回一个  Promise 。它最多需要有两个参数：Promise 的成功和失败情况的回调函数。")和[`catch()`]42294 "catch() 方法返回一个Promise，并且处理拒绝的情况。它的行为与调用Promise.prototype.then(undefined, onRejected) 相同。 (事实上, calling obj.catch(onRejected) 内部calls obj.then(undefined, onRejected)).")中各写一次的情况。

## Syntax<a name="Syntax"></a>

```
p.finally(onFinally);

p.finally(function() {
   // settled (resolved 或 rejected)
});

```

### Parameters<a name="Parameters"></a>
<dl><dt id=''>`onFinally`</dt><dd>`Promise`状态改变后的回调函数。</dd></dl>
### Return value<a name="Return_value"></a>


返回一个设置了finally回调函数的[`Promise`]4107 "Promise 对象用于表示一个异步操作的最终状态（完成或失败），以及其返回的值。")对象。


## Description<a name="Description"></a>


`finally()`虽然与`.then(onFinally, onFinally)`类似，它们不同的是：


* 调用内联函数时，不需要多次声明该函数或为该函数创建一个变量保存它。
* 由于无法知道`promise`的最终状态，所以`finally`的回调函数中不接收任何参数，它仅用于无论最终结果如何都要执行的情况。
* 与`Promise.resolve(2).then(() => {}, () => {})`（resolved的结果为`undefined`）不同，`Promise.resolve(2).finally(() => {})`resolved的结果为`2`。
* 同样，`Promise.reject(3).then(() => {}, () => {})`(resolved 的结果为`undefined`),`Promise.reject(3).finally(() => {})`rejected 的结果为`3`。


**Note:**A`throw`(or returning a rejected promise) in the`finally`callback will reject the new promise with the rejection reason specified when calling`throw()`.



## Examples<a name="Examples"></a>

```
let isLoading = true;

fetch(myRequest).then(function(response) {
    var contentType = response.headers.get("content-type");
    if(contentType && contentType.includes("application/json")) {
      return response.json();
    }
    throw new TypeError("Oops, we haven't got JSON!");
  })
  .then(function(json) { /* process your JSON further */ })
  .catch(function(error) { console.log(error); })
  .finally(function() { isLoading = false; });
```

## Specifications<a name="Specifications"></a>

Specification | Status | Comment 
[TC39 proposal]45985 "") | Stage 4 |  


## Browser compatibility<a name="Browser_compatibility"></a>
[新的兼容性表格正在测试中<i></i>]3360 "")

 | <abbr>Desktop<i></i></abbr> | <abbr>Mobile<i></i></abbr> | <abbr>Server<i></i></abbr> 
 | <abbr>Chrome<i></i></abbr> | <abbr>Edge<i></i></abbr> | <abbr>Firefox<i></i></abbr> | <abbr>Internet Explorer<i></i></abbr> | <abbr>Opera<i></i></abbr> | <abbr>Safari<i></i></abbr> | <abbr>Android webview<i></i></abbr> | <abbr>Chrome for Android<i></i></abbr> | <abbr>Edge Mobile<i></i></abbr> | <abbr>Firefox for Android<i></i></abbr> | <abbr>Opera for Android<i></i></abbr> | <abbr>iOS Safari<i></i></abbr> | <abbr>Samsung Internet<i></i></abbr> | <abbr>Node.js<i></i></abbr> 
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  | 
Basic support | <abbr>Full support</abbr>63 | <abbr>No support</abbr>No | <abbr>Full support</abbr>58 | <abbr>No support</abbr>No | <abbr>Full support</abbr>50 | <abbr>No support</abbr>No | <abbr>Full support</abbr>63 | <abbr>Full support</abbr>63 | <abbr>No support</abbr>No | <abbr>Full support</abbr>58 | <abbr>Full support</abbr>50 | <abbr>No support</abbr>No | <abbr>No support</abbr>No | <abbr>No support</abbr>No 


### Legend<a name="Legend"></a>
<dl><dt id=''><abbr>Full support</abbr></dt><dd>Full support</dd><dt id=''><abbr>No support</abbr></dt><dd>No support</dd></dl>

## See also<a name="See_also"></a>

* [`Promise`]4107 "Promise 对象用于表示一个异步操作的最终状态（完成或失败），以及其返回的值。")
* [`Promise.prototype.then()`]41433 "then() 方法返回一个  Promise 。它最多需要有两个参数：Promise 的成功和失败情况的回调函数。")
* [`Promise.prototype.catch()`]42294 "catch() 方法返回一个Promise，并且处理拒绝的情况。它的行为与调用Promise.prototype.then(undefined, onRejected) 相同。 (事实上, calling obj.catch(onRejected) 内部calls obj.then(undefined, onRejected)).")



