---
manual:Javascript
version:0
lang:zh
rawUrl:https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error
---





通过**Error**的构造器可以创建一个错误对象。当运行时错误产生时，Error的实例对象会被抛出。Error对象也可用于用户自定义的异常的基础对象。下面列出了各种内建的标准错误类型。


## 语法<a name="Syntax"></a>

```
new Error([message[, fileName[,lineNumber]]])
```

### 参数<a name="Parameters"></a>
<dl><dt id=''>`message`</dt><dd>可选。人类可阅读的错误描述信息。</dd></dl><dl><dt id=''>`fileName`<i></i></dt><dd>可选。被创建的Error对象的fileName属性值。默认是调用Error构造器代码所在的文件 的名字。</dd></dl><dl><dt id=''>`lineNumber`<i></i></dt><dd>可选。被创建的Error对象的lineNumber属性值。默认是调用Error构造器代码所在的文件的行号。</dd></dl>
## 描述<a name="Description"></a>


当代码运行时的发生错误，会创建新的Error对象，并将其抛出。



该页面描述了Error对象自身的使用,以及其构造函数的使用. 关于Error实例的内部属性和方法,请看[`Error.prototype`]41983 "所有 Error 与 非标准Error 的实例都继承自 Error.prototype。同所有构造器函数一样，你可以在构造器的 prototype 上添加属性或者方法，使其在所有该构造器的实例上生效。").


### Error 类型<a name="Error_types"></a>


除了通用的Error构造函数外，JavaScript还有6个其他类型的错误构造函数。更多客户端异常,详见[Exception Handling Statements]41993 "en/JavaScript/Guide/Statements#Exception Handling Statements")。

<dl><dt id=''>**[`EvalError`]40525 "本对象代表了一个关于 eval 函数的错误.此异常不再会被JavaScript抛出，但是EvalError对象仍然保持兼容性.")**</dt><dd>创建一个error实例，表示错误的原因：与[`eval()`]40573 "执行指定代码之后的返回值。如果返回值为空，返回undefined")有关。</dd><dt id=''>**[`InternalError`]40529 "InternalError 对象表示出现在JavaScript引擎内部的错误。 例如： "InternalError: too much recursion"（内部错误：递归过深）。")<i></i>**</dt><dd>创建一个代表Javascript引擎内部错误的异常抛出的实例。 如: &quot;递归太多&quot;.</dd></dl><dl><dt id=''>**[`RangeError`]22962 "RangeError对象标明一个错误，当一个值不在其所允许的范围或者集合中。")**</dt><dd>创建一个error实例，表示错误的原因：数值变量或参数超出其有效范围。</dd></dl><dl><dt id=''>**[`ReferenceError`]40538 "ReferenceError（引用错误） 对象表明一个不存在的变量被引用。")**</dt><dd>创建一个error实例，表示错误的原因：无效引用。</dd></dl><dl><dt id=''>**[`SyntaxError`]40564 "SyntaxError 对象代表尝试解析语法上不合法的代码的错误。")**</dt><dd>创建一个error实例，表示错误的原因：[`eval()`]40573 "执行指定代码之后的返回值。如果返回值为空，返回undefined")在解析代码的过程中发生的语法错误。</dd></dl><dl><dt id=''>**[`TypeError`]3682 "TypeError（类型错误） 对象用来表示值的类型非预期类型时发生的错误。")**</dt><dd>创建一个error实例，表示错误的原因：变量或参数不属于有效类型。</dd></dl><dl><dt id=''>**[`URIError`]40565 "URIError 对象用来表示以一种错误的方式使用全局URI处理函数而产生的错误。")**</dt><dd>创建一个error实例，表示错误的原因：给[`encodeURI()`]39937 "encodeURI()  函数通过将特定字符的每个实例替换为一个、两个、三或四转义序列来对统一资源标识符 (URI) 进行编码 (该字符的 UTF-8 编码仅为四转义序列)由两个 "代理" 字符组成)。")或[`decodeURl()`]40569 "decodeURI() 函数解码一个由encodeURI 先前创建的统一资源标识符（URI）或类似的例程。")传递的参数无效。</dd></dl>
## 属性<a name="Properties"></a>
<dl><dt id=''>[`Error.prototype`]41983 "所有 Error 与 非标准Error 的实例都继承自 Error.prototype。同所有构造器函数一样，你可以在构造器的 prototype 上添加属性或者方法，使其在所有该构造器的实例上生效。")</dt><dd>允许添加属性到Error实例.</dd></dl>
## 方法<a name="Methods"></a>


全局Error对象自身不包含任何方法,但从原型链中继承了一些方法.


## `Error`实例<a name="Error_instances"></a>


All[`Error`]27232 "The Error constructor creates an error object. Instances of Error objects are thrown when runtime errors occur. The Error object can also be used as a base object for user-defined exceptions. See below for standard built-in error types.")instances and instances of[non-generic errors]41184 "The Error constructor creates an error object. Instances of Error objects are thrown when runtime errors occur. The Error object can also be used as a base object for user-defined exceptions. See below for standard built-in error types.")inherit from`Error.prototype`. As with all constructor functions, you can use the prototype of the constructor to add properties or methods to all instances created with that constructor.


### 属性<a name="属性"></a>

### Standard properties<a name="Standard_properties"></a>
<dl><dt id=''>`Error.prototype.constructor`</dt><dd>Specifies the function that created an instance&#39;s prototype.</dd><dt id=''>[`Error.prototype.message`]41994 "The message property is a human-readable description of the error.")</dt><dd>Error message.</dd><dt id=''>[`Error.prototype.name`]41995 "The name property represents a name for the type of error. The initial value is "Error".")</dt><dd>Error name.</dd></dl>
### Vendor-specific extensions<a name="Vendor-specific_extensions"></a>


**Non-standard**<br></br>This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.




#### Microsoft<a name="Microsoft"></a>
<dl><dt id=''>[`Error.prototype.description`]41996 "The documentation about this has not yet been written; please consider contributing!")</dt><dd>Error description. Similar to[`message`]41994 "The message property is a human-readable description of the error.").</dd><dt id=''>[`Error.prototype.number`]41997 "The documentation about this has not yet been written; please consider contributing!")</dt><dd>Error number.</dd></dl>
#### Mozilla<a name="Mozilla"></a>
<dl><dt id=''>[`Error.prototype.fileName`]41998 "The fileName property contains the path to the file that raised this error.")</dt><dd>Path to file that raised this error.</dd><dt id=''>[`Error.prototype.lineNumber`]41999 "The lineNumber property contains the line number in the file that raised this error.")</dt><dd>Line number in file that raised this error.</dd><dt id=''>[`Error.prototype.columnNumber`]42000 "The columnNumber property contains the column number in the line of the file that raised this error.")</dt><dd>Column number in line that raised this error.</dd><dt id=''>[`Error.prototype.stack`]42001 "The non-standard stack property of Error objects offer a trace of which functions were called, in what order, from which line and file, and with what arguments. The stack string proceeds from the most recent calls to earlier ones, leading back to the original global scope call.")</dt><dd>Stack trace.</dd></dl>
### 方法<a name="方法"></a>
<dl><dt id=''>[`Error.prototype.toSource()`]42002 "The toSource() method returns code that could eval to the same error.")<i></i></dt><dd>Returns a string containing the source of the specified[`Error`]27232 "The Error constructor creates an error object. Instances of Error objects are thrown when runtime errors occur. The Error object can also be used as a base object for user-defined exceptions. See below for standard built-in error types.")object; you can use this value to create a new object. Overrides the[`Object.prototype.toSource()`]22333 "The toSource() method returns a string representing the source code of the object.")method.</dd><dt id=''>[`Error.prototype.toString()`]42003 "The toString() method returns a string representing the specified Error object.")</dt><dd>Returns a string representing the specified object. Overrides the[`Object.prototype.toString()`]22335 "The toString() method returns a string representing the object.")method.</dd></dl>

## 例子<a name="Examples"></a>

### 例1: 抛出一个基本错误<a name="Example:_Throwing_a_generic_error"></a>


通常你会使用[`throw`]40640 "throw语句用来抛出一个用户自定义的异常。当前函数的执行将被停止（throw之后的语句将不会执行），并且控制将被传递到调用堆栈中的第一个catch块。如果调用者函数中没有catch块，程序将会终止。")关键字来抛出你创建的Error对象。可以使用[`try...catch`]40641 "try...catch语句将能引发错误的代码放在try块中，并且对应一个响应，然后有异常被抛出。")结构来处理异常:


```
try {
    throw new Error("Whoops!");
} catch (e) {
    alert(e.name + ": " + e.message);
}
```

### 例2: 处理一个特定错误<a name="Example:_Handling_a_specific_error"></a>


你可以通过判断异常的类型来特定处理某一类的异常,即判断[`constructor`]41698 "返回创建实例对象的 Object 构造函数的引用。注意，此属性的值是对函数本身的引用，而不是一个包含函数名称的字符串。对原始类型来说，如1，true和"test"，该值只可读。")属性，当使用现代Javascript引擎时,可使用[`instanceof`]40606 "instanceof 运算符用来测试一个对象在其原型链中是否存在一个构造函数的 prototype 属性。")关键字：


```
try {
    foo.bar();
} catch (e) {
    if (e instanceof EvalError) {
        alert(e.name + ": " + e.message);
    } else if (e instanceof RangeError) {
        alert(e.name + ": " + e.message);
    }
    // ... etc
}
```

### 示例: 自定义异常类型<a name="示例_自定义异常类型"></a>


你可能希望自定义基于Error的异常类型，使得你能够 throw new MyError() 并可以使用`instanceof MyError`来检查某个异常的类型. 这种需求的通用解决方法如下.



注意，在FireFox中抛出自定义类型的异常会显示不正确的行号和文件名。




参考[&quot;What&#39;s a good way to extend Error in JavaScript?&quot; discussion on Stackoverflow]42004 "").


```
// Create a new object, that prototypally inherits from the Error constructor.
function MyError(message) {
  this.name = 'MyError';
  this.message = message || 'Default Message';
  this.stack = (new Error()).stack;
}
MyError.prototype = Object.create(Error.prototype);
MyError.prototype.constructor = MyError;

try {
  throw new MyError();
} catch (e) {
  console.log(e.name);     // 'MyError'
  console.log(e.message);  // 'Default Message'
}

try {
  throw new MyError('custom message');
} catch (e) {
  console.log(e.name);     // 'MyError'
  console.log(e.message);  // 'custom message'
}
```






















## 规范<a name="规范"></a>

Specification | Status | Comment 
ECMAScript 1st Edition. | Standard | Initial definition. Implemented in JavaScript 1.1. 
[ECMAScript 5.1 (ECMA-262)<br></br><small>Error</small>]42005 "") | Standard |  
[ECMAScript 2015 (6th Edition, ECMA-262)<br></br><small>Error</small>]42006 "") | Standard |  
[ECMAScript Latest Draft (ECMA-262)<br></br><small>Error</small>]42007 "") | Draft |  


## 浏览器兼容性<a name="浏览器兼容性"></a>


**[We&#39;re converting our compatibility data into a machine-readable JSON format]3344 "")**. This compatibility table still uses the old format, because we haven&#39;t yet converted the data it contains.**[Find out how you can help!]3392 "")**


* 
* 

Feature | Chrome | Firefox (Gecko) | Internet Explorer | Opera | Safari 
Basic support | (Yes) | (Yes) | (Yes) | (Yes) | (Yes) 





## 相关链接<a name="See_also"></a>

* [`Error.prototype`]41983 "所有 Error 与 非标准Error 的实例都继承自 Error.prototype。同所有构造器函数一样，你可以在构造器的 prototype 上添加属性或者方法，使其在所有该构造器的实例上生效。")
* [`throw`]40640 "throw语句用来抛出一个用户自定义的异常。当前函数的执行将被停止（throw之后的语句将不会执行），并且控制将被传递到调用堆栈中的第一个catch块。如果调用者函数中没有catch块，程序将会终止。")
* [`try...catch`]40641 "try...catch语句将能引发错误的代码放在try块中，并且对应一个响应，然后有异常被抛出。")



